import { exec } from 'dugite'
import { chmod, mkdir, readdir, rename, rm, writeFile } from 'fs/promises'
import { join } from 'path'

import { GitHookType, HookLoadout, HookScript } from './loadout-types'

const DISPATCHER_MARKER = '# Auto-generated by Madness Desktop'

/**
 * Returns the thin dispatcher script for a given hook type.
 * The dispatcher runs all executable *.sh scripts in the hook's .d/ directory.
 */
export function getDispatcherScript(hookType: GitHookType): string {
  return `#!/usr/bin/env bash
${DISPATCHER_MARKER} — do not edit
DIR="$(cd "$(dirname "$0")/${hookType}.d" 2>/dev/null && pwd)"
[[ -d "$DIR" ]] || exit 0
for script in "$DIR"/*.sh; do
  [[ -x "$script" ]] && "$script" "$@"
done
`
}

/**
 * Install a loadout into a repository.
 *
 * Creates .githooks/ with dispatcher scripts and .d/ subdirectories
 * containing the individual hook scripts, then sets core.hooksPath.
 */
export async function installLoadout(
  repoPath: string,
  loadout: HookLoadout,
  allScripts: ReadonlyArray<HookScript>,
  disabledScripts: ReadonlyArray<string> = []
): Promise<void> {
  const hooksDir = join(repoPath, '.githooks')
  await mkdir(hooksDir, { recursive: true })

  // Resolve which scripts belong to this loadout
  const scripts = loadout.scriptIds
    .map(id => allScripts.find(s => s.id === id))
    .filter((s): s is HookScript => s !== undefined)

  // Group scripts by hook type
  const byType = new Map<GitHookType, HookScript[]>()
  for (const script of scripts) {
    const group = byType.get(script.hookType) ?? []
    group.push(script)
    byType.set(script.hookType, group)
  }

  // Write dispatcher + .d/ scripts for each hook type
  for (const [hookType, hookScripts] of byType) {
    // Write dispatcher
    const dispatcherPath = join(hooksDir, hookType)
    await writeFile(dispatcherPath, getDispatcherScript(hookType), {
      mode: 0o755,
    })

    // Create .d/ directory
    const dDir = join(hooksDir, `${hookType}.d`)
    await mkdir(dDir, { recursive: true })

    // Write individual scripts
    for (const hs of hookScripts) {
      const disabled = disabledScripts.includes(hs.id)
      const filename = disabled ? `${hs.id}.sh.disabled` : `${hs.id}.sh`
      const scriptPath = join(dDir, filename)
      await writeFile(scriptPath, hs.script, { mode: 0o755 })
    }
  }

  // Set core.hooksPath
  await exec(['config', 'core.hooksPath', '.githooks'], repoPath)
}

/**
 * Uninstall all loadout-managed hooks from a repository.
 *
 * Only removes dispatcher scripts that contain our marker and their .d/
 * directories. Leaves any non-managed hooks untouched.
 */
export async function uninstallLoadout(repoPath: string): Promise<void> {
  const hooksDir = join(repoPath, '.githooks')

  const entries = await readdir(hooksDir, { withFileTypes: true }).catch(
    () => []
  )

  for (const entry of entries) {
    if (entry.isDirectory() && entry.name.endsWith('.d')) {
      await rm(join(hooksDir, entry.name), { recursive: true, force: true })

      // Remove the matching dispatcher if it's ours
      const dispatcherName = entry.name.replace(/\.d$/, '')
      const dispatcherPath = join(hooksDir, dispatcherName)
      try {
        const { readFile } = await import('fs/promises')
        const content = await readFile(dispatcherPath, 'utf8')
        if (content.includes(DISPATCHER_MARKER)) {
          await rm(dispatcherPath, { force: true })
        }
      } catch {
        // dispatcher doesn't exist or unreadable — fine
      }
    }
  }

  // Unset core.hooksPath if it points to .githooks
  const result = await exec(
    ['config', '-z', '--get', 'core.hooksPath'],
    repoPath
  )
  if (result.exitCode === 0 && result.stdout.split('\0')[0] === '.githooks') {
    await exec(['config', '--unset', 'core.hooksPath'], repoPath)
  }
}

/**
 * Toggle a single script within an installed loadout on disk.
 * Renames between .sh and .sh.disabled.
 */
export async function toggleScriptOnDisk(
  repoPath: string,
  script: HookScript,
  enabled: boolean
): Promise<void> {
  const dDir = join(repoPath, '.githooks', `${script.hookType}.d`)
  const enabledPath = join(dDir, `${script.id}.sh`)
  const disabledPath = join(dDir, `${script.id}.sh.disabled`)

  if (enabled) {
    await rename(disabledPath, enabledPath).catch(() => {})
    await chmod(enabledPath, 0o755).catch(() => {})
  } else {
    await rename(enabledPath, disabledPath).catch(() => {})
  }
}

/**
 * Detect which loadout (if any) is installed in a repository by
 * scanning .githooks/ for .d/ directories and matching script files.
 */
export async function detectInstalledScripts(
  repoPath: string
): Promise<ReadonlyArray<{ scriptId: string; enabled: boolean }>> {
  const hooksDir = join(repoPath, '.githooks')
  const results: Array<{ scriptId: string; enabled: boolean }> = []

  const entries = await readdir(hooksDir, { withFileTypes: true }).catch(
    () => []
  )

  for (const entry of entries) {
    if (!entry.isDirectory() || !entry.name.endsWith('.d')) {
      continue
    }

    const dDir = join(hooksDir, entry.name)
    const scripts = await readdir(dDir).catch(() => [])

    for (const file of scripts) {
      if (file.endsWith('.sh')) {
        results.push({ scriptId: file.replace(/\.sh$/, ''), enabled: true })
      } else if (file.endsWith('.sh.disabled')) {
        results.push({
          scriptId: file.replace(/\.sh\.disabled$/, ''),
          enabled: false,
        })
      }
    }
  }

  return results
}
