/**
 * Preload script — runs in the preload world before the renderer page loads.
 * Exposes a safe IPC bridge via contextBridge so the renderer can communicate
 * with the main process without requiring nodeIntegration.
 *
 * The registry maps listener IDs (generated by the renderer) to the actual
 * ipcRenderer handler functions, enabling correct removeListener semantics
 * despite contextBridge not guaranteeing stable function identity across calls.
 */
import { contextBridge, ipcRenderer } from 'electron'

const registry = new Map<string, (...args: any[]) => void>()

contextBridge.exposeInMainWorld('electronBridge', {
  invoke(channel: string, ...args: any[]): Promise<any> {
    return ipcRenderer.invoke(channel, ...args)
  },

  send(channel: string, ...args: any[]): void {
    ipcRenderer.send(channel, ...args)
  },

  // eslint-disable-next-line no-sync
  sendSync(channel: string, ...args: any[]): any {
    return ipcRenderer.sendSync(channel, ...args)
  },

  on(channel: string, id: string, callback: (...args: any[]) => void): void {
    const handler = (_event: Electron.IpcRendererEvent, ...args: any[]) =>
      callback(...args)
    registry.set(id, handler)
    ipcRenderer.on(channel, handler)
  },

  once(channel: string, id: string, callback: (...args: any[]) => void): void {
    const handler = (_event: Electron.IpcRendererEvent, ...args: any[]) => {
      registry.delete(id)
      callback(...args)
    }
    registry.set(id, handler)
    ipcRenderer.once(channel, handler)
  },

  removeListener(channel: string, id: string): void {
    const handler = registry.get(id)
    if (handler !== undefined) {
      ipcRenderer.removeListener(channel, handler)
      registry.delete(id)
    }
  },
})
