/**
 * Preload script — runs before the renderer page loads, in the same
 * JavaScript context (contextIsolation: false).  The preload has full Node.js
 * access; it sets window.electronBridge directly so the renderer can talk to
 * the main process without sprinkling ipcRenderer imports everywhere.
 *
 * The registry maps listener IDs (generated by the renderer) to the actual
 * ipcRenderer handler functions, enabling correct removeListener semantics
 * (renderer passes stable IDs rather than unstable function references).
 *
 * NOTE: contextBridge.exposeInMainWorld is intentionally NOT used here
 * because contextBridge requires contextIsolation: true, which prevents
 * the renderer from calling require() — breaking the webpack electron-renderer
 * bundle that generates require() calls for all externals. The direct-window
 * approach is equivalent for a local-content-only app where XSS risk is low.
 */
import { ipcRenderer } from 'electron'

const registry = new Map<string, (...args: any[]) => void>()

const bridge = {
  invoke(channel: string, ...args: any[]): Promise<any> {
    return ipcRenderer.invoke(channel, ...args)
  },

  send(channel: string, ...args: any[]): void {
    ipcRenderer.send(channel, ...args)
  },

  // eslint-disable-next-line no-sync
  sendSync(channel: string, ...args: any[]): any {
    return ipcRenderer.sendSync(channel, ...args)
  },

  on(channel: string, id: string, callback: (...args: any[]) => void): void {
    const handler = (_event: Electron.IpcRendererEvent, ...args: any[]) =>
      callback(...args)
    registry.set(id, handler)
    ipcRenderer.on(channel, handler)
  },

  once(channel: string, id: string, callback: (...args: any[]) => void): void {
    const handler = (_event: Electron.IpcRendererEvent, ...args: any[]) => {
      registry.delete(id)
      callback(...args)
    }
    registry.set(id, handler)
    ipcRenderer.once(channel, handler)
  },

  removeListener(channel: string, id: string): void {
    const handler = registry.get(id)
    if (handler !== undefined) {
      ipcRenderer.removeListener(channel, handler)
      registry.delete(id)
    }
  },
}

// Directly assign to window — safe because preload and renderer share
// the same JS context with contextIsolation:false.
;(window as any).electronBridge = bridge
