// Auto-generated from MadnessThemes personality JSONs — do not edit

export interface DesktopStrings {
  commitTo: string
  summaryPlaceholder: string
  descriptionPlaceholder: string
  amend: string
  committing: string
  generateMessage: string
  undoCommit: string
  push: string
  pull: string
  fetch: string
  publishBranch: string
  publishRepository: string
  fetching: string
  pushing: string
  pulling: string
  newBranch: string
  createBranch: string
  deleteBranch: string
  renameBranch: string
  switchBranch: string
  currentBranch: string
  branchName: string
  noBranches: string
  changesTitle: string
  noLocalChanges: string
  discardChanges: string
  discardAll: string
  stashChanges: string
  undo: string
  cloneRepository: string
  addRepository: string
  removeRepository: string
  repositorySettings: string
  openInTerminal: string
  viewOnGitHub: string
  historyTitle: string
  noHistory: string
  resolveConflicts: string
  abortMerge: string
  continueRebase: string
  abortRebase: string
  ok: string
  cancel: string
  discard: string
  continue: string
  dismiss: string
}

export interface ThemeStrings {
  save: string
  cancel: string
  close: string
  edit: string
  delete: string
  reset: string
  refresh: string
  loading: string
  error: string
  success: string
  failed: string
  confirm: string
  search: string
  filter: string
  clear: string
  apply: string
  desktop: DesktopStrings
}

export const defaultStrings: ThemeStrings = {
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  edit: "Edit",
  delete: "Delete",
  reset: "Reset",
  refresh: "Refresh",
  loading: "Loading...",
  error: "An error occurred",
  success: "Success!",
  failed: "Operation failed",
  confirm: "Confirm",
  search: "Search",
  filter: "Filter",
  clear: "Clear",
  apply: "Apply",
  desktop: {
    commitTo: "Commit to {branch}",
    summaryPlaceholder: "Summary (required)",
    descriptionPlaceholder: "Description",
    amend: "Amend last commit",
    committing: "Committing…",
    generateMessage: "Generate commit message",
    undoCommit: "Undo",
    push: "Push origin",
    pull: "Pull origin",
    fetch: "Fetch origin",
    publishBranch: "Publish branch",
    publishRepository: "Publish repository",
    fetching: "Fetching…",
    pushing: "Pushing…",
    pulling: "Pulling…",
    newBranch: "New branch",
    createBranch: "Create branch",
    deleteBranch: "Delete branch",
    renameBranch: "Rename branch",
    switchBranch: "Switch branch",
    currentBranch: "Current branch",
    branchName: "Branch name",
    noBranches: "No branches",
    changesTitle: "Changes",
    noLocalChanges: "No local changes",
    discardChanges: "Discard changes",
    discardAll: "Discard all changes",
    stashChanges: "Stash changes",
    undo: "Undo",
    cloneRepository: "Clone repository",
    addRepository: "Add repository",
    removeRepository: "Remove repository",
    repositorySettings: "Repository settings",
    openInTerminal: "Open in terminal",
    viewOnGitHub: "View on GitHub",
    historyTitle: "History",
    noHistory: "No history",
    resolveConflicts: "Resolve conflicts",
    abortMerge: "Abort merge",
    continueRebase: "Continue rebase",
    abortRebase: "Abort rebase",
    ok: "OK",
    cancel: "Cancel",
    discard: "Discard",
    continue: "Continue",
    dismiss: "Dismiss",
  },
}

export const personalityStrings: Record<string, ThemeStrings> = {
  "banana": {
    save: "Stash in Tree",
    cancel: "Drop Banana",
    close: "Descend from Tree",
    edit: "Re-Groom",
    delete: "Chuck Away",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Peeling bananas...",
    error: "Tree branch snapped",
    success: "Successfully harvested!",
    failed: "Banana slipped - operation halted",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "biomedical": {
    save: "Save Results",
    cancel: "Cancel",
    close: "Close",
    edit: "Modify",
    delete: "Archive",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Processing...",
    error: "Error detected",
    success: "Success!",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "corporate-clean": {
    save: "Save Changes",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    delete: "Remove",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Loading...",
    error: "An error occurred",
    success: "Success",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "corporate-drone": {
    save: "Commit Strategic Adjustments",
    cancel: "Abort Current Operation",
    close: "Conclude Active Session",
    edit: "Refine Active Configuration",
    delete: "Decommission Selected Asset",
    reset: "Reinitialize Parameters to Baseline",
    refresh: "Synchronize Data Feed",
    loading: "Processing request – please maintain productivity posture...",
    error: "⚠️ Unexpected optimization opportunity detected",
    success: "✅ Mission executed with exemplary compliance!",
    failed: "🚫 Initiative encountered resistance – please realign and retry",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "cyan-lab": {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Processing...",
    error: "An error occurred",
    success: "Success!",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "debug": {
    save: "common.save",
    cancel: "common.cancel",
    close: "common.close",
    edit: "common.edit",
    delete: "common.delete",
    reset: "common.reset",
    refresh: "Refresh",
    loading: "common.loading",
    error: "common.error",
    success: "common.success",
    failed: "common.failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "dwarf": {
    save: "Chisel into Stone",
    cancel: "Cave-In",
    close: "Seal Mine Entrance",
    edit: "Re-forge",
    delete: "Collapse Tunnel",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Smelting ore...",
    error: "Cave collapse detected",
    success: "Successfully mined!",
    failed: "Pickaxe broke - excavation halted",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "gunmetal": {
    save: "Lock-On",
    cancel: "RTB",
    close: "Dock",
    edit: "Reconfigure",
    delete: "Destroy",
    reset: "Reset Systems",
    refresh: "Rescan",
    loading: "Launching...",
    error: "System Critical",
    success: "Mission complete!",
    failed: "Sortie failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "labops": {
    save: "Log Entry",
    cancel: "Abort",
    close: "Close Station",
    edit: "Amend",
    delete: "Decommission",
    reset: "Reset to Baseline",
    refresh: "Rescan",
    loading: "Processing sample...",
    error: "Instrument malfunction detected",
    success: "Protocol completed successfully",
    failed: "Procedure failed — review logs",
    confirm: "Confirm",
    search: "Query",
    filter: "Filter Specimens",
    clear: "Clear Parameters",
    apply: "Apply Protocol",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "mad-wizard": {
    save: "Archive Findings",
    cancel: "Abandon Experiment",
    close: "Seal Apparatus",
    edit: "Modify Apparatus",
    delete: "Banish to Void",
    reset: "Reset Apparatus",
    refresh: "Refresh Portal",
    loading: "Void Tunneling...",
    error: "Mystical interference detected",
    success: "Experiment successfully archived!",
    failed: "Apparatus malfunction - investigation halted",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "standard": {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Loading...",
    error: "An error occurred",
    success: "Success!",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "templar-light": {
    save: "Inscribe in Codex",
    cancel: "Abandon",
    close: "Close the Gate",
    edit: "Amend",
    delete: "Strike from Record",
    reset: "Restore to Covenant",
    refresh: "Consult Oracle",
    loading: "Consulting the Codex...",
    error: "A darkness has disrupted the vigil",
    success: "The decree is sealed",
    failed: "The sacred rite has faltered",
    confirm: "Swear Oath",
    search: "Search the Codex",
    filter: "Filter by Virtue",
    clear: "Clear the Parchment",
    apply: "Invoke Decree",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
}

export function getThemeStrings(personality: string): ThemeStrings {
  return personalityStrings[personality] ?? defaultStrings
}
