// Auto-generated from MadnessThemes personality JSONs — do not edit

export interface DesktopStrings {
  commitTo: string
  summaryPlaceholder: string
  descriptionPlaceholder: string
  amend: string
  committing: string
  generateMessage: string
  undoCommit: string
  push: string
  pull: string
  fetch: string
  publishBranch: string
  publishRepository: string
  fetching: string
  pushing: string
  pulling: string
  newBranch: string
  createBranch: string
  deleteBranch: string
  renameBranch: string
  switchBranch: string
  currentBranch: string
  branchName: string
  noBranches: string
  changesTitle: string
  noLocalChanges: string
  discardChanges: string
  discardAll: string
  stashChanges: string
  undo: string
  cloneRepository: string
  addRepository: string
  removeRepository: string
  repositorySettings: string
  openInTerminal: string
  viewOnGitHub: string
  historyTitle: string
  noHistory: string
  resolveConflicts: string
  abortMerge: string
  continueRebase: string
  abortRebase: string
  ok: string
  cancel: string
  discard: string
  continue: string
  dismiss: string
}

export interface ThemeStrings {
  save: string
  cancel: string
  close: string
  edit: string
  delete: string
  reset: string
  refresh: string
  loading: string
  error: string
  success: string
  failed: string
  confirm: string
  search: string
  filter: string
  clear: string
  apply: string
  desktop: DesktopStrings
}

export const defaultStrings: ThemeStrings = {
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  edit: "Edit",
  delete: "Delete",
  reset: "Reset",
  refresh: "Refresh",
  loading: "Loading...",
  error: "An error occurred",
  success: "Success!",
  failed: "Operation failed",
  confirm: "Confirm",
  search: "Search",
  filter: "Filter",
  clear: "Clear",
  apply: "Apply",
  desktop: {
    commitTo: "Commit to {branch}",
    summaryPlaceholder: "Summary (required)",
    descriptionPlaceholder: "Description",
    amend: "Amend last commit",
    committing: "Committing…",
    generateMessage: "Generate commit message",
    undoCommit: "Undo",
    push: "Push origin",
    pull: "Pull origin",
    fetch: "Fetch origin",
    publishBranch: "Publish branch",
    publishRepository: "Publish repository",
    fetching: "Fetching…",
    pushing: "Pushing…",
    pulling: "Pulling…",
    newBranch: "New branch",
    createBranch: "Create branch",
    deleteBranch: "Delete branch",
    renameBranch: "Rename branch",
    switchBranch: "Switch branch",
    currentBranch: "Current branch",
    branchName: "Branch name",
    noBranches: "No branches",
    changesTitle: "Changes",
    noLocalChanges: "No local changes",
    discardChanges: "Discard changes",
    discardAll: "Discard all changes",
    stashChanges: "Stash changes",
    undo: "Undo",
    cloneRepository: "Clone repository",
    addRepository: "Add repository",
    removeRepository: "Remove repository",
    repositorySettings: "Repository settings",
    openInTerminal: "Open in terminal",
    viewOnGitHub: "View on GitHub",
    historyTitle: "History",
    noHistory: "No history",
    resolveConflicts: "Resolve conflicts",
    abortMerge: "Abort merge",
    continueRebase: "Continue rebase",
    abortRebase: "Abort rebase",
    ok: "OK",
    cancel: "Cancel",
    discard: "Discard",
    continue: "Continue",
    dismiss: "Dismiss",
  },
}

export const personalityStrings: Record<string, ThemeStrings> = {
  "banana": {
    save: "Stash in Tree",
    cancel: "Drop Banana",
    close: "Descend from Tree",
    edit: "Re-Groom",
    delete: "Chuck Away",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Peeling bananas...",
    error: "Tree branch snapped",
    success: "Successfully harvested!",
    failed: "Banana slipped - operation halted",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Stash to {branch}",
      summaryPlaceholder: "Banana summary (required)",
      descriptionPlaceholder: "Jungle notes",
      amend: "Re-peel last stash",
      committing: "Stashing…",
      generateMessage: "Conjure banana note",
      undoCommit: "Un-stash",
      push: "Fling to origin",
      pull: "Gather from origin",
      fetch: "Sniff origin",
      publishBranch: "Plant branch",
      publishRepository: "Plant grove",
      fetching: "Sniffing…",
      pushing: "Flinging…",
      pulling: "Gathering…",
      newBranch: "New branch",
      createBranch: "Grow branch",
      deleteBranch: "Prune branch",
      renameBranch: "Rebrand branch",
      switchBranch: "Swing branch",
      currentBranch: "This branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Fresh peels",
      noLocalChanges: "No fresh peels",
      discardChanges: "Toss peels",
      discardAll: "Discard all changes",
      stashChanges: "Hoard peels",
      undo: "Un-swing",
      cloneRepository: "Clone grove",
      addRepository: "Add grove",
      removeRepository: "Drop grove",
      repositorySettings: "Grove config",
      openInTerminal: "Open vine shell",
      viewOnGitHub: "Peek on GitHub",
      historyTitle: "Tree rings",
      noHistory: "No tree rings",
      resolveConflicts: "Untangle vines",
      abortMerge: "Abort merge",
      continueRebase: "Keep rebasing",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Drop banana",
      discard: "Toss it",
      continue: "Swing on",
      dismiss: "Shoo",
    },
  },
  "biomedical": {
    save: "Save Results",
    cancel: "Cancel",
    close: "Close",
    edit: "Modify",
    delete: "Archive",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Processing...",
    error: "Error detected",
    success: "Success!",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Log to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last log entry",
      committing: "Logging…",
      generateMessage: "Generate log entry",
      undoCommit: "Reverse",
      push: "Transmit to registry",
      pull: "Sync from registry",
      fetch: "Fetch from registry",
      publishBranch: "Register branch",
      publishRepository: "Register repository",
      fetching: "Fetching…",
      pushing: "Transmitting…",
      pulling: "Syncing…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Modifications",
      noLocalChanges: "No local modifications",
      discardChanges: "Discard modifications",
      discardAll: "Discard all modifications",
      stashChanges: "Set aside samples",
      undo: "Reverse",
      cloneRepository: "Clone repository",
      addRepository: "Register repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "Chronicle",
      noHistory: "No records",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "corporate-clean": {
    save: "Save Changes",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    delete: "Remove",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Loading...",
    error: "An error occurred",
    success: "Success",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "corporate-drone": {
    save: "Commit Strategic Adjustments",
    cancel: "Abort Current Operation",
    close: "Conclude Active Session",
    edit: "Refine Active Configuration",
    delete: "Decommission Selected Asset",
    reset: "Reinitialize Parameters to Baseline",
    refresh: "Synchronize Data Feed",
    loading: "Processing request – please maintain productivity posture...",
    error: "⚠️ Unexpected optimization opportunity detected",
    success: "✅ Mission executed with exemplary compliance!",
    failed: "🚫 Initiative encountered resistance – please realign and retry",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit Deliverables to {branch}",
      summaryPlaceholder: "Executive Summary (required)",
      descriptionPlaceholder: "Strategic Narrative",
      amend: "Revise Prior Commitment",
      committing: "Committing Deliverables…",
      generateMessage: "Auto-Draft Commit Narrative",
      undoCommit: "Roll Back",
      push: "Push to Upstream Stakeholders",
      pull: "Pull Upstream Alignment",
      fetch: "Sync Upstream Status",
      publishBranch: "Publish Workstream",
      publishRepository: "Onboard Repository to HQ",
      fetching: "Syncing Upstream…",
      pushing: "Pushing Upstream…",
      pulling: "Pulling Alignment…",
      newBranch: "New Workstream",
      createBranch: "Provision Workstream",
      deleteBranch: "Decommission Workstream",
      renameBranch: "Rebrand Workstream",
      switchBranch: "Pivot to Workstream",
      currentBranch: "Active Workstream",
      branchName: "Workstream Identifier",
      noBranches: "No Active Workstreams",
      changesTitle: "Pending Deliverables",
      noLocalChanges: "Zero Pending Deliverables",
      discardChanges: "Discard Deliverables",
      discardAll: "Discard All Local Changes",
      stashChanges: "Park Deliverables for Later",
      undo: "Roll Back",
      cloneRepository: "Replicate Repository",
      addRepository: "Onboard Repository",
      removeRepository: "Offboard Repository",
      repositorySettings: "Repository Governance",
      openInTerminal: "Launch Command Console",
      viewOnGitHub: "Review on GitHub",
      historyTitle: "Audit Trail",
      noHistory: "No Audit Trail Yet",
      resolveConflicts: "Reconcile Conflicts",
      abortMerge: "Abort Merge",
      continueRebase: "Resume Rebase",
      abortRebase: "Abort Rebase",
      ok: "OK",
      cancel: "Abort Current Operation",
      discard: "Discard",
      continue: "Proceed",
      dismiss: "Acknowledge & Dismiss",
    },
  },
  "cyan-lab": {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Processing...",
    error: "An error occurred",
    success: "Success!",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Sync origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Syncing…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Active branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "Workspace clear",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "debug": {
    save: "common.save",
    cancel: "common.cancel",
    close: "common.close",
    edit: "common.edit",
    delete: "common.delete",
    reset: "common.reset",
    refresh: "Refresh",
    loading: "common.loading",
    error: "common.error",
    success: "common.success",
    failed: "common.failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "desktop.commitTo",
      summaryPlaceholder: "desktop.summaryPlaceholder",
      descriptionPlaceholder: "desktop.descriptionPlaceholder",
      amend: "desktop.amend",
      committing: "desktop.committing",
      generateMessage: "desktop.generateMessage",
      undoCommit: "desktop.undoCommit",
      push: "desktop.push",
      pull: "desktop.pull",
      fetch: "desktop.fetch",
      publishBranch: "desktop.publishBranch",
      publishRepository: "desktop.publishRepository",
      fetching: "desktop.fetching",
      pushing: "desktop.pushing",
      pulling: "desktop.pulling",
      newBranch: "desktop.newBranch",
      createBranch: "desktop.createBranch",
      deleteBranch: "desktop.deleteBranch",
      renameBranch: "desktop.renameBranch",
      switchBranch: "desktop.switchBranch",
      currentBranch: "desktop.currentBranch",
      branchName: "desktop.branchName",
      noBranches: "desktop.noBranches",
      changesTitle: "desktop.changesTitle",
      noLocalChanges: "desktop.noLocalChanges",
      discardChanges: "desktop.discardChanges",
      discardAll: "desktop.discardAll",
      stashChanges: "desktop.stashChanges",
      undo: "desktop.undo",
      cloneRepository: "desktop.cloneRepository",
      addRepository: "desktop.addRepository",
      removeRepository: "desktop.removeRepository",
      repositorySettings: "desktop.repositorySettings",
      openInTerminal: "desktop.openInTerminal",
      viewOnGitHub: "desktop.viewOnGitHub",
      historyTitle: "desktop.historyTitle",
      noHistory: "desktop.noHistory",
      resolveConflicts: "desktop.resolveConflicts",
      abortMerge: "desktop.abortMerge",
      continueRebase: "desktop.continueRebase",
      abortRebase: "desktop.abortRebase",
      ok: "desktop.ok",
      cancel: "desktop.cancel",
      discard: "desktop.discard",
      continue: "desktop.continue",
      dismiss: "desktop.dismiss",
    },
  },
  "dwarf": {
    save: "Chisel into Stone",
    cancel: "Cave-In",
    close: "Seal Mine Entrance",
    edit: "Re-forge",
    delete: "Collapse Tunnel",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Smelting ore...",
    error: "Cave collapse detected",
    success: "Successfully mined!",
    failed: "Pickaxe broke - excavation halted",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Chisel into {branch}",
      summaryPlaceholder: "Claim summary (required)",
      descriptionPlaceholder: "Mining notes",
      amend: "Re-forge last chisel",
      committing: "Chiselin'…",
      generateMessage: "Conjure claim summary",
      undoCommit: "Unchisel",
      push: "Haul to origin",
      pull: "Haul from origin",
      fetch: "Survey origin",
      publishBranch: "Stake the vein",
      publishRepository: "Stake the quarry",
      fetching: "Surveyin'…",
      pushing: "Haulin' up…",
      pulling: "Haulin' down…",
      newBranch: "New vein",
      createBranch: "Dig new vein",
      deleteBranch: "Collapse vein",
      renameBranch: "Re-mark vein",
      switchBranch: "Switch vein",
      currentBranch: "Current vein",
      branchName: "Vein name",
      noBranches: "No veins",
      changesTitle: "Ore Changes",
      noLocalChanges: "No fresh ore",
      discardChanges: "Discard ore changes",
      discardAll: "Collapse all changes",
      stashChanges: "Cache the ore",
      undo: "Undo",
      cloneRepository: "Clone quarry",
      addRepository: "Add quarry",
      removeRepository: "Seal quarry away",
      repositorySettings: "Quarry forge",
      openInTerminal: "Open in tunnel shell",
      viewOnGitHub: "View on Ore Archive",
      historyTitle: "Strata Chronicle",
      noHistory: "No strata yet",
      resolveConflicts: "Settle the cave-in",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "Aye",
      cancel: "Cave-In",
      discard: "Abandon",
      continue: "Press on",
      dismiss: "Wave off",
    },
  },
  "gunmetal": {
    save: "Lock-On",
    cancel: "RTB",
    close: "Dock",
    edit: "Reconfigure",
    delete: "Destroy",
    reset: "Reset Systems",
    refresh: "Rescan",
    loading: "Launching...",
    error: "System Critical",
    success: "Mission complete!",
    failed: "Sortie failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Draft message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Deploy branch",
      publishRepository: "Deploy repo",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Active branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repo",
      addRepository: "Add repo",
      removeRepository: "Remove repo",
      repositorySettings: "Repo config",
      openInTerminal: "Open terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "Log",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "labops": {
    save: "Log Entry",
    cancel: "Abort",
    close: "Close Station",
    edit: "Amend",
    delete: "Decommission",
    reset: "Reset to Baseline",
    refresh: "Rescan",
    loading: "Processing sample...",
    error: "Instrument malfunction detected",
    success: "Protocol completed successfully",
    failed: "Procedure failed — review logs",
    confirm: "Confirm",
    search: "Query",
    filter: "Filter Specimens",
    clear: "Clear Parameters",
    apply: "Apply Protocol",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Change summary (required)",
      descriptionPlaceholder: "Runbook notes",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Draft commit message",
      undoCommit: "Roll back",
      push: "Push to origin",
      pull: "Pull from origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Register repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Cut branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Active branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Pending changes",
      noLocalChanges: "Working tree clean",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Roll back",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository config",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "Deploy log",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "mad-wizard": {
    save: "Archive Findings",
    cancel: "Abandon Experiment",
    close: "Seal Apparatus",
    edit: "Modify Apparatus",
    delete: "Banish to Void",
    reset: "Reset Apparatus",
    refresh: "Refresh Portal",
    loading: "Void Tunneling...",
    error: "Mystical interference detected",
    success: "Experiment successfully archived!",
    failed: "Apparatus malfunction - investigation halted",
    confirm: "Confirm",
    search: "Seek",
    filter: "Sift",
    clear: "Dispel",
    apply: "Invoke",
    desktop: {
      commitTo: "Inscribe to {branch}",
      summaryPlaceholder: "Incantation summary (required)",
      descriptionPlaceholder: "Arcane annotations",
      amend: "Reforge last sigil",
      committing: "Inscribing…",
      generateMessage: "Divine commit sigil",
      undoCommit: "Unbind",
      push: "Cast to origin",
      pull: "Draw from origin",
      fetch: "Scry origin",
      publishBranch: "Manifest timeline",
      publishRepository: "Manifest grimoire",
      fetching: "Scrying…",
      pushing: "Casting…",
      pulling: "Drawing…",
      newBranch: "New timeline",
      createBranch: "Conjure timeline",
      deleteBranch: "Banish timeline",
      renameBranch: "Rename timeline",
      switchBranch: "Shift timeline",
      currentBranch: "Current timeline",
      branchName: "Timeline name",
      noBranches: "No timelines",
      changesTitle: "Alterations",
      noLocalChanges: "No local alterations",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash in aether",
      undo: "Undo",
      cloneRepository: "Clone grimoire",
      addRepository: "Bind grimoire",
      removeRepository: "Remove grimoire",
      repositorySettings: "Grimoire config",
      openInTerminal: "Open conjuring shell",
      viewOnGitHub: "View on GitHub",
      historyTitle: "Chronicle",
      noHistory: "No chronicle",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "standard": {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    reset: "Reset",
    refresh: "Refresh",
    loading: "Loading...",
    error: "An error occurred",
    success: "Success!",
    failed: "Operation failed",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    apply: "Apply",
    desktop: {
      commitTo: "Commit to {branch}",
      summaryPlaceholder: "Summary (required)",
      descriptionPlaceholder: "Description",
      amend: "Amend last commit",
      committing: "Committing…",
      generateMessage: "Generate commit message",
      undoCommit: "Undo",
      push: "Push origin",
      pull: "Pull origin",
      fetch: "Fetch origin",
      publishBranch: "Publish branch",
      publishRepository: "Publish repository",
      fetching: "Fetching…",
      pushing: "Pushing…",
      pulling: "Pulling…",
      newBranch: "New branch",
      createBranch: "Create branch",
      deleteBranch: "Delete branch",
      renameBranch: "Rename branch",
      switchBranch: "Switch branch",
      currentBranch: "Current branch",
      branchName: "Branch name",
      noBranches: "No branches",
      changesTitle: "Changes",
      noLocalChanges: "No local changes",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Stash changes",
      undo: "Undo",
      cloneRepository: "Clone repository",
      addRepository: "Add repository",
      removeRepository: "Remove repository",
      repositorySettings: "Repository settings",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "View on GitHub",
      historyTitle: "History",
      noHistory: "No history",
      resolveConflicts: "Resolve conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Cancel",
      discard: "Discard",
      continue: "Continue",
      dismiss: "Dismiss",
    },
  },
  "templar-light": {
    save: "Inscribe in Codex",
    cancel: "Abandon",
    close: "Close the Gate",
    edit: "Amend",
    delete: "Strike from Record",
    reset: "Restore to Covenant",
    refresh: "Consult Oracle",
    loading: "Consulting the Codex...",
    error: "A darkness has disrupted the vigil",
    success: "The decree is sealed",
    failed: "The sacred rite has faltered",
    confirm: "Swear Oath",
    search: "Search the Codex",
    filter: "Filter by Virtue",
    clear: "Clear the Parchment",
    apply: "Invoke Decree",
    desktop: {
      commitTo: "Inscribe to {branch}",
      summaryPlaceholder: "Decree (required)",
      descriptionPlaceholder: "Scripture",
      amend: "Amend last decree",
      committing: "Inscribing…",
      generateMessage: "Compose decree",
      undoCommit: "Revoke",
      push: "Send to origin",
      pull: "Receive from origin",
      fetch: "Summon from origin",
      publishBranch: "Consecrate branch",
      publishRepository: "Consecrate archive",
      fetching: "Summoning…",
      pushing: "Sending…",
      pulling: "Receiving…",
      newBranch: "New order",
      createBranch: "Found order",
      deleteBranch: "Delete branch",
      renameBranch: "Rename order",
      switchBranch: "Cross to order",
      currentBranch: "Present order",
      branchName: "Order name",
      noBranches: "No orders",
      changesTitle: "Amendments",
      noLocalChanges: "No local amendments",
      discardChanges: "Discard changes",
      discardAll: "Discard all changes",
      stashChanges: "Lay in reliquary",
      undo: "Revoke",
      cloneRepository: "Copy archive",
      addRepository: "Enter archive",
      removeRepository: "Remove archive",
      repositorySettings: "Archive configuration",
      openInTerminal: "Open in terminal",
      viewOnGitHub: "Behold on GitHub",
      historyTitle: "Chronicle",
      noHistory: "No chronicle",
      resolveConflicts: "Reconcile conflicts",
      abortMerge: "Abort merge",
      continueRebase: "Continue rebase",
      abortRebase: "Abort rebase",
      ok: "OK",
      cancel: "Withdraw",
      discard: "Discard",
      continue: "Advance",
      dismiss: "Dismiss",
    },
  },
}

export function getThemeStrings(personality: string): ThemeStrings {
  return personalityStrings[personality] ?? defaultStrings
}
