import { ActionDefinition } from './hotkey-types'

/**
 * All bindable actions with their default keybindings.
 * Menu actions have their accelerators extracted from build-default-menu.ts.
 * Non-menu actions are available for user binding but unbound by default.
 */
export const DefaultActionDefinitions: ReadonlyArray<ActionDefinition> = [
  // ─── File Menu ───────────────────────────────────────────────────────────────

  {
    id: 'create-repository',
    label: 'New Repository',
    category: 'file',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+N',
    isMenuAction: true,
  },
  {
    id: 'add-local-repository',
    label: 'Add Local Repository',
    category: 'file',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+O',
    isMenuAction: true,
  },
  {
    id: 'clone-repository',
    label: 'Clone Repository',
    category: 'file',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+Shift+O',
    isMenuAction: true,
  },
  {
    id: 'show-preferences',
    label: 'Settings',
    category: 'file',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+,',
    isMenuAction: true,
  },

  // ─── Edit Menu ───────────────────────────────────────────────────────────────

  {
    id: 'select-all',
    label: 'Select All',
    category: 'edit',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+A',
    isMenuAction: true,
  },
  {
    id: 'find-text',
    label: 'Find',
    category: 'edit',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+F',
    isMenuAction: true,
  },

  // ─── View Menu ───────────────────────────────────────────────────────────────

  {
    id: 'show-changes',
    label: 'Show Changes',
    category: 'view',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+1',
    isMenuAction: true,
  },
  {
    id: 'show-history',
    label: 'Show History',
    category: 'view',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+2',
    isMenuAction: true,
  },
  {
    id: 'choose-repository',
    label: 'Show Repository List',
    category: 'view',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+T',
    isMenuAction: true,
  },
  {
    id: 'show-branches',
    label: 'Show Branches List',
    category: 'view',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+B',
    isMenuAction: true,
  },
  {
    id: 'show-worktrees',
    label: 'Show Worktrees List',
    category: 'view',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Alt+W',
    isMenuAction: true,
  },
  {
    id: 'go-to-commit-message',
    label: 'Go to Summary',
    category: 'view',
    context: 'changes-tab',
    defaultBinding: 'CmdOrCtrl+G',
    isMenuAction: true,
  },
  {
    id: 'show-stashed-changes',
    label: 'Show Stashed Changes',
    category: 'view',
    context: 'repository',
    defaultBinding: 'Ctrl+H',
    isMenuAction: true,
  },
  {
    id: 'hide-stashed-changes',
    label: 'Hide Stashed Changes',
    category: 'view',
    context: 'repository',
    defaultBinding: 'Ctrl+H',
    isMenuAction: true,
  },
  {
    id: 'toggle-changes-filter',
    label: 'Toggle Changes Filter',
    category: 'view',
    context: 'changes-tab',
    defaultBinding: 'CmdOrCtrl+L',
    isMenuAction: true,
  },
  {
    id: 'toggle-group-changes-by-folder',
    label: 'Toggle Folder Grouping',
    category: 'view',
    context: 'changes-tab',
    defaultBinding: 'CmdOrCtrl+Shift+L',
    isMenuAction: true,
  },
  {
    id: 'increase-active-resizable-width',
    label: 'Expand Active Resizable',
    category: 'view',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+9',
    isMenuAction: true,
  },
  {
    id: 'decrease-active-resizable-width',
    label: 'Contract Active Resizable',
    category: 'view',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+8',
    isMenuAction: true,
  },

  // ─── Repository Menu ─────────────────────────────────────────────────────────

  {
    id: 'push',
    label: 'Push',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+P',
    isMenuAction: true,
  },
  {
    id: 'force-push',
    label: 'Force Push',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: true,
  },
  {
    id: 'pull',
    label: 'Pull',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+P',
    isMenuAction: true,
  },
  {
    id: 'fetch',
    label: 'Fetch',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+T',
    isMenuAction: true,
  },
  {
    id: 'remove-repository',
    label: 'Remove Repository',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Backspace',
    isMenuAction: true,
  },
  {
    id: 'view-repository-on-github',
    label: 'View on GitHub',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+G',
    isMenuAction: true,
  },
  {
    id: 'open-in-shell',
    label: 'Open in Shell',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+`',
    isMenuAction: true,
  },
  {
    id: 'toggle-integrated-terminal',
    label: 'Toggle Integrated Terminal',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'Ctrl+`',
    isMenuAction: true,
  },
  {
    id: 'toggle-dotfiles-panel',
    label: 'Toggle Dotfiles Panel',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Alt+`',
    isMenuAction: true,
  },
  {
    id: 'open-working-directory',
    label: 'Show in File Manager',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+F',
    isMenuAction: true,
  },
  {
    id: 'open-external-editor',
    label: 'Open in External Editor',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+A',
    isMenuAction: true,
  },
  {
    id: 'open-with-external-editor',
    label: 'Open With External Editor',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+Alt+A',
    isMenuAction: true,
  },
  {
    id: 'create-issue-in-repository-on-github',
    label: 'Create Issue on GitHub',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+I',
    isMenuAction: true,
  },
  {
    id: 'create-worktree',
    label: 'New Worktree',
    category: 'repository',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+W',
    isMenuAction: true,
  },
  {
    id: 'show-repository-settings',
    label: 'Repository Settings',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: true,
  },

  // ─── Branch Menu ─────────────────────────────────────────────────────────────

  {
    id: 'create-branch',
    label: 'New Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+N',
    isMenuAction: true,
  },
  {
    id: 'rename-branch',
    label: 'Rename Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+R',
    isMenuAction: true,
  },
  {
    id: 'delete-branch',
    label: 'Delete Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+D',
    isMenuAction: true,
  },
  {
    id: 'discard-all-changes',
    label: 'Discard All Changes',
    category: 'branch',
    context: 'changes-tab',
    defaultBinding: 'CmdOrCtrl+Shift+Backspace',
    isMenuAction: true,
  },
  {
    id: 'stash-all-changes',
    label: 'Stash All Changes',
    category: 'branch',
    context: 'changes-tab',
    defaultBinding: 'CmdOrCtrl+Shift+S',
    isMenuAction: true,
  },
  {
    id: 'update-branch-with-contribution-target-branch',
    label: 'Update from Default Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+U',
    isMenuAction: true,
  },
  {
    id: 'compare-to-branch',
    label: 'Compare to Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+B',
    isMenuAction: true,
  },
  {
    id: 'merge-branch',
    label: 'Merge into Current Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+M',
    isMenuAction: true,
  },
  {
    id: 'squash-and-merge-branch',
    label: 'Squash and Merge',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+H',
    isMenuAction: true,
  },
  {
    id: 'rebase-branch',
    label: 'Rebase Current Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+E',
    isMenuAction: true,
  },
  {
    id: 'compare-on-github',
    label: 'Compare on GitHub',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Shift+C',
    isMenuAction: true,
  },
  {
    id: 'branch-on-github',
    label: 'View Branch on GitHub',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Alt+B',
    isMenuAction: true,
  },
  {
    id: 'preview-pull-request',
    label: 'Preview Pull Request',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+Alt+P',
    isMenuAction: true,
  },
  {
    id: 'open-pull-request',
    label: 'Create / View Pull Request',
    category: 'branch',
    context: 'repository',
    defaultBinding: 'CmdOrCtrl+R',
    isMenuAction: true,
  },

  // ─── Non-Menu Dispatcher Actions (unbound by default) ────────────────────────

  // ─── Commit & Changes ────────────────────────────────────────────────────────

  {
    id: 'commit-included-changes',
    label: 'Commit Changes',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'undo-commit',
    label: 'Undo Last Commit',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'start-amending-repository',
    label: 'Amend Last Commit',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'stop-amending-repository',
    label: 'Stop Amending',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'discard-changes',
    label: 'Discard Selected Changes',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'change-include-all-files',
    label: 'Toggle All Files',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'generate-commit-message',
    label: 'Generate Commit Message (Copilot)',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'generate-local-ai-commit-message',
    label: 'Generate Commit Message (Local AI)',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'create-stash-for-current-branch',
    label: 'Stash Changes',
    category: 'commit',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'pop-stash',
    label: 'Pop Stash',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'drop-stash',
    label: 'Drop Stash',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },

  // ─── Branch Operations ───────────────────────────────────────────────────────

  {
    id: 'checkout-branch',
    label: 'Checkout Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'delete-local-branch',
    label: 'Delete Local Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'delete-remote-branch',
    label: 'Delete Remote Branch',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'start-rebase',
    label: 'Start Rebase',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'abort-rebase',
    label: 'Abort Rebase',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'continue-rebase',
    label: 'Continue Rebase',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'cherry-pick',
    label: 'Cherry Pick',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'abort-cherry-pick',
    label: 'Abort Cherry Pick',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'continue-cherry-pick',
    label: 'Continue Cherry Pick',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'squash',
    label: 'Squash Commits',
    category: 'branch',
    context: 'history-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'reorder-commits',
    label: 'Reorder Commits',
    category: 'branch',
    context: 'history-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'show-rebase-dialog',
    label: 'Show Rebase Dialog',
    category: 'branch',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'reset-to-commit',
    label: 'Reset to Commit',
    category: 'branch',
    context: 'history-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'revert-commit',
    label: 'Revert Commit',
    category: 'branch',
    context: 'history-tab',
    defaultBinding: null,
    isMenuAction: false,
  },

  // ─── Repository Operations ───────────────────────────────────────────────────

  {
    id: 'publish-repository',
    label: 'Publish Repository',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'refresh-repository',
    label: 'Refresh Repository',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'create-tag',
    label: 'Create Tag',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'delete-tag',
    label: 'Delete Tag',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'toggle-favorite-repository',
    label: 'Toggle Favorite',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'relocate-repository',
    label: 'Relocate Repository',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'show-create-tag-dialog',
    label: 'Show Create Tag Dialog',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'show-delete-tag-dialog',
    label: 'Show Delete Tag Dialog',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'open-shell-here',
    label: 'Open Shell Here',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'open-in-external-editor',
    label: 'Open in Editor',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },

  // ─── Pull Requests ───────────────────────────────────────────────────────────

  {
    id: 'create-pull-request',
    label: 'Create Pull Request',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'show-pull-request',
    label: 'View Pull Request',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'checkout-pull-request',
    label: 'Checkout Pull Request',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'start-pull-request',
    label: 'Start Pull Request',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'refresh-pull-requests',
    label: 'Refresh Pull Requests',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },

  // ─── Submodules ──────────────────────────────────────────────────────────────

  {
    id: 'init-all-submodules',
    label: 'Init All Submodules',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'sync-submodule',
    label: 'Sync Submodule',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'pull-all-submodules',
    label: 'Pull All Submodules',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'push-all-submodules',
    label: 'Push All Submodules',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'show-submodule-management',
    label: 'Show Submodule Manager',
    category: 'repository',
    context: 'repository',
    defaultBinding: null,
    isMenuAction: false,
  },

  // ─── Navigation & View ───────────────────────────────────────────────────────

  {
    id: 'close-popup',
    label: 'Close Dialog',
    category: 'navigation',
    context: 'global',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'close-foldout',
    label: 'Close Panel',
    category: 'navigation',
    context: 'global',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'load-next-commit-batch',
    label: 'Load More Commits',
    category: 'navigation',
    context: 'history-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'focus-commit-message',
    label: 'Focus Commit Message',
    category: 'navigation',
    context: 'changes-tab',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'toggle-sidebar',
    label: 'Toggle Sidebar',
    category: 'navigation',
    context: 'global',
    defaultBinding: null,
    isMenuAction: false,
  },
  {
    id: 'cycle-theme-next',
    label: 'Next Madness Theme',
    category: 'navigation',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+}',
    isMenuAction: false,
  },
  {
    id: 'cycle-theme-prev',
    label: 'Previous Madness Theme',
    category: 'navigation',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+{',
    isMenuAction: false,
  },
  {
    id: 'navigate-repo-back',
    label: 'Back (Repo History)',
    category: 'navigation',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+Alt+Left',
    isMenuAction: false,
  },
  {
    id: 'navigate-repo-forward',
    label: 'Forward (Repo History)',
    category: 'navigation',
    context: 'global',
    defaultBinding: 'CmdOrCtrl+Alt+Right',
    isMenuAction: false,
  },

  // ─── Misc ────────────────────────────────────────────────────────────────────

  {
    id: 'show-about',
    label: 'About',
    category: 'misc',
    context: 'global',
    defaultBinding: null,
    isMenuAction: true,
  },
  {
    id: 'show-keybindings',
    label: 'Keyboard Shortcuts',
    category: 'misc',
    context: 'global',
    defaultBinding: null,
    isMenuAction: true,
  },
  {
    id: 'install-darwin-cli',
    label: 'Install CLI Tool',
    category: 'misc',
    context: 'global',
    defaultBinding: null,
    isMenuAction: true,
  },
  {
    id: 'edit-global-git-config',
    label: 'Edit Git Config',
    category: 'misc',
    context: 'global',
    defaultBinding: null,
    isMenuAction: false,
  },
]

/**
 * Index of action definitions by ID for fast lookup.
 */
export const ActionDefinitionMap: ReadonlyMap<string, ActionDefinition> =
  new Map(DefaultActionDefinitions.map(def => [def.id, def]))
